# Generated by Django 4.2.7 on 2023-11-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
