# Generated by Django 4.2.7 on 2023-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('regular', "Regular - Can't Delete Members"), ('admin', 'Admin - Can Delete Members')], default='regular', max_length=10),
        ),
    ]
